apiVersion: monitoring.openshift.io/v1
kind: AlertingRule
metadata:
  name: example
  namespace: openshift-monitoring
spec:
  groups:
  - name: example-rules
    rules:
    - alert: ExampleAlert
      for: 1m
      expr: vector(1)
      labels:
        severity: warning
      annotations:
        message: This is an example alert.
