apiVersion: v1
kind: Pod
metadata:
  name: pod-rootuid
  namespace: demo-scc
spec:
  containers:
  - name: test-app
    image: busybox:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    securityContext:
      runAsUser: 0
