apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
  namespace: demo-scc
spec:
  containers:
  - name: tomcat
    image: tomcat:latest
    ports:
    - containerPort: 8080
    securityContext:
      privileged: true
