apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: demo-scc
spec:
  containers:
  - name: test-app
    image: busybox:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: host-path-vol
      mountPath: /mnt/host
  volumes:
  - name: host-path-vol
    hostPath:
      path: /tmp
      type: DirectoryOrCreate
